import "./globals.css";
import { Barlow, Barlow_Condensed, Bellefair } from "next/font/google";

const barlow = Barlow({
  weight: ["400", "800", "900"],
  subsets: ["latin"],
  variable: "--font-barlow",
});

const barlowCondensed = Barlow_Condensed({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-barlowCondensed",
});

const bellefair = Bellefair({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bellefair",
});

export const metadata = {
  title: "Space Tourism",
  description: "Generated by DK Coding",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${barlow.variable} ${barlowCondensed.variable} ${bellefair.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
